### ISSUE TITLE
Feature: Local Loading of WordPress Update Popup Window 

### ISSUE THREAD

**Issue by BlaineMoore** [ryansechrest/github-updater-demo#4]
Displaying information about the plugin update using the WordPress popup rather than loading a separate changelog HTML page (and feeding that information from the releases)

When looking at update details, the current class loads an external HTML page and just replaces the WordPress login window with the changelog found there:

![Current Changelog Screenshot](https://github.com/ryansechrest/github-updater-demo/assets/8483773/073fdd60-8085-416c-b2c6-ffc61d4ba765)

It would not be too difficult to implement update data that would show additional information:

![WordPress Update Popup screenshot](https://github.com/ryansechrest/github-updater-demo/assets/8483773/4d34d55a-3045-4681-9167-3820f73f897f)

For a minimum viable update, the description can be pulled from the plugin header, and the changelog could be pulled from an individual release (per issue #3 ) or by parsing the full releases changelog. Potential updates could also include searching for icon files in the plugin or specifically adding links to the icons/headers in the plugin headers or through function calls (similar to how the tested version and branch are currently implemented.)

(I have not implemented this yet but will be tackling it soon.)

**Comment by ryansechrest** [comment]
Hello! I was under the impression that the WordPress pop-up you screenshotted was also a remote file, but generated by wordpress.org, because that's where the plugin would normally be hosted. Because of this, I opted for a simple HTML file served through GitHub pages to act as the changelog. I will say that I don't love my solution, because it doesn't work if the repository is private. I have considered retrieving the HTML file over the API and then rendering that locally on the site, so it's not reliant on GitHub pages to work.

**Comment by BlaineMoore** [comment]
No, if you use the `plugins_api` filter instead of the `admin_url` you can just pass a plugin object with all of the criteria and it'll create it for you. I haven't pushed anything up to my fork yet, but here's my current status on that:

![image](https://github.com/user-attachments/assets/b5294de2-e85e-4136-be03-f457c8e2aecf)

Right now I have it pulling the icons and banners out of the header (or ignoring if they aren't present) but am going to update it to allow for an absolute URL or relative URL so it doesn't have to ping a third-party website. I currently have it adding the changelog directly from the Plugin URI where you were loading previously, though once I add in using the releases functionality instead of a specific branch I'll just have it load the changelog dynamically from the releases themselves so there's no need to keep an external page up to date or public.

**Comment by BlaineMoore** [comment]
I've added [a changelog branch](https://github.com/BlaineMoore/github-updater-demo/tree/changelog) that now populates the changelog based on versions in GitHub (converting basic markdown to HTML, which also happens on the description now as well though that's not on that branch.)

![image](https://github.com/user-attachments/assets/bb55b879-2c39-440f-b256-b064085bb11a)

It'll support up to the 30 most recent releases per the current GitHub API defaults.

Welcome to use any of that code if you like for your version, though I think going forward I'll be diverging more from what you wanted since next step will be getting versions directly from GitHub rather than directly from the working tree. (Though I'll likely leave an option to use a specific branch as it works now since I can see use cases where it'd be handy to have a plugin option page where you can choose stable release or pre-release or cutting edge from a branch.)

Thanks for the motivation and providing the base that has most of this working, it's been a lot of fun to play around with and make fit my use case needs.

**Comment by ryansechrest** [comment]
That's really cool. Once I circle back to this part, I do see myself reworking this to using the standard modal, now that I know it's possible, and remove the need to host a separate page to load within the modal.

And no problem! Glad this PHP class got you started and led you to making it the best version that it can be for you. That's why I published it. :)
